let selector strings start with list selectors
Allow something like:

```
cat example.md | mdq '- foo'
```

We do this by creating a hidden flag named ` ` (just a space), so that
`- foo` is really the `-{space}` flag followed by an argument `foo`. We
then use that to recreate the `- foo` selector string.

clap arg groups let us validate that the user doesn't specify both this
list-starting selector and a normal selector:

```
$ mdq '# hello' ✅
$ mdq '- world' ✅

$ mdq '# hello' '- world' ❌
error: the argument '[selectors]' cannot be used with '-  <selectors starting with list>'
```

The error message isn't perfect, but this is good enough.

resolves #102